### ISSUE TITLE
level undefined method error

### ISSUE THREAD

**Issue by lando2319** [emilbaehr/automatic-app-landing-page#84]
Hello, 

I've been successfully using this theme for years, but now somethings wrong, I cloned this repo into a dir

then, `bundle install`

this successfully installs the gem, however when I run, `bundle exec jekyll server`

I get the following

```
$ bundle exec jekyll serve
jekyll 3.9.3 | Error:  undefined method `[]' for nil:NilClass
/Users/mikeland/.rvm/gems/ruby-3.2.1/gems/logger-1.6.0/lib/logger.rb:384:in `level': undefined method `[]' for nil:NilClass (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll/configuration.rb:157:in `config_files'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll.rb:113:in `configuration'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll/command.rb:43:in `configuration_from_options'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:89:in `start'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/bin/jekyll:25:in `load'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/bin/jekyll:25:in `<main>'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
        from /Users/mikeland/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by lando2319** [comment]
I ended up adding `webrick` to my gem file, bundle update on github-pages, this put my jekyll at 3.10.0 and it finally started working
